//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcapitulos
    {
        public tblcapitulos()
        {
            this.tblcapituloservers = new HashSet<tblcapituloservers>();
        }
    
        public int idcapitulo { get; set; }
        public int idserie { get; set; }
        public int idtemporada { get; set; }
        public Nullable<int> consecutivo { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> alta { get; set; }
        public string miniatura { get; set; }
        public string descripcion { get; set; }
        public bool status { get; set; }
    
        public virtual tblseries tblseries { get; set; }
        public virtual tbltemporadas tbltemporadas { get; set; }
        public virtual ICollection<tblcapituloservers> tblcapituloservers { get; set; }
    }
}
