//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblseriegenero
    {
        public int idserie { get; set; }
        public int idgenero { get; set; }
        public bool status { get; set; }
    
        public virtual tblgeneros tblgeneros { get; set; }
        public virtual tblseries tblseries { get; set; }
    }
}
