//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblseries
    {
        public tblseries()
        {
            this.tblcapitulos = new HashSet<tblcapitulos>();
            this.tblseriegenero = new HashSet<tblseriegenero>();
            this.tblserielike = new HashSet<tblserielike>();
            this.tblserienolike = new HashSet<tblserienolike>();
            this.tblserieseguir = new HashSet<tblserieseguir>();
            this.tblusuariofavoritoseries = new HashSet<tblusuariofavoritoseries>();
        }
    
        public int idserie { get; set; }
        public string nombre { get; set; }
        public int año { get; set; }
        public string descripcion { get; set; }
        public string poster { get; set; }
        public System.DateTime alta { get; set; }
        public string trailer { get; set; }
        public bool condicion { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<tblcapitulos> tblcapitulos { get; set; }
        public virtual ICollection<tblseriegenero> tblseriegenero { get; set; }
        public virtual ICollection<tblserielike> tblserielike { get; set; }
        public virtual ICollection<tblserienolike> tblserienolike { get; set; }
        public virtual ICollection<tblserieseguir> tblserieseguir { get; set; }
        public virtual ICollection<tblusuariofavoritoseries> tblusuariofavoritoseries { get; set; }
    }
}
