//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltipocuentas
    {
        public tbltipocuentas()
        {
            this.tblusuarios = new HashSet<tblusuarios>();
        }
    
        public int idtipocuenta { get; set; }
        public string descripcion { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<tblusuarios> tblusuarios { get; set; }
    }
}
