//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltemporadas
    {
        public tbltemporadas()
        {
            this.tblcapitulos = new HashSet<tblcapitulos>();
        }
    
        public int idtemporada { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual ICollection<tblcapitulos> tblcapitulos { get; set; }
    }
}
