//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrauserTv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusuarios
    {
        public tblusuarios()
        {
            this.tblserielike = new HashSet<tblserielike>();
            this.tblserienolike = new HashSet<tblserienolike>();
            this.tblserieseguir = new HashSet<tblserieseguir>();
            this.tblusuariofavoritoseries = new HashSet<tblusuariofavoritoseries>();
        }
    
        public int idusuario { get; set; }
        public int idtipocuenta { get; set; }
        public string password { get; set; }
        public string usuario { get; set; }
        public bool status { get; set; }
    
        public virtual tblpersonas tblpersonas { get; set; }
        public virtual ICollection<tblserielike> tblserielike { get; set; }
        public virtual ICollection<tblserienolike> tblserienolike { get; set; }
        public virtual ICollection<tblserieseguir> tblserieseguir { get; set; }
        public virtual tbltipocuentas tbltipocuentas { get; set; }
        public virtual ICollection<tblusuariofavoritoseries> tblusuariofavoritoseries { get; set; }
    }
}
